👌 IMPROVE: Rename startRow/maxRows to from/size, respectively.
coldbox-modules/cbelasticsearch pull request #124
Opened 2023-04-19 03:41 UTC by michaelborn

New syntax:

```js
searchBuilder.setFrom( 11 );
searchBuilder.setSize( 10 );
```

Still keeps backwards-compatible shims in place for the old parameter names:

```js
var searchBuilder = variables.model.new( variables.testIndexName, "testdocs", {
					maxRows : 15,
					startRow : 16
				} );
searchBuilder.setStartRow( 51 );
searchBuilder.setMaxRows( 50 );
```

- [x] Renames `startRow` to `from` 💪
- [x] Renames `maxRows` to `size` 🔨
- [x] Keeps support for older names in both `.new()` and setter methods 🎉
- [x] Adds test for new names 🤖
- [x] Adds pagination docs to `Search.md` 📖

2023-04-19 12:46 UTC, jclausen requested changes

2023-04-19 12:46 UTC, jclausen commented on models/SearchBuilder.cfc
> +	 * !DEPRECATED - Backwards compatible setter for max result size
Use the javadoc `@deprectated` annotation.  Then it shows up better when Docbox generates from the source.

2023-04-19 12:46 UTC, jclausen commented on models/SearchBuilder.cfc
> +	 * !DEPRECATED - Backwards compatible setter for result start offset
Same note as above

2023-04-19 12:51 UTC, jclausen commented on models/SearchBuilder.cfc
> +	 * !DEPRECATED - Backwards compatible setter for max result size
Since this is deprecated, can you also replace the usage of `setMaxRows` and `setStartRow` in this repository. I see one `setMaxRows` used in the Migration manager

2023-04-19 15:19 UTC, michaelborn commented
Added `@deprecated` note for DocBox, dropped Manager's use of `setMaxRows()`. I see no use of these deprecated methods outside of the tests which are explicit tests for backwards compatibility.

2023-04-20 12:59 UTC, jclausen commented
@michaelborn This one has merge conflicts now.

2023-04-20 17:35 UTC, merged